### ISSUE TITLE
Pass number of retries as part of `opts` parameter.

### ISSUE THREAD

**Issue by timolinn** [miraclx/xresilient#1]
https://github.com/miraclx/xresilient/blob/3e5d13b78f89e7f782603ff9fe38cf984ad6082e/lib/index.js#L8

I could want to to reduce the number of retries, especially for server's with limited resources.

**Comment by miraclx** [comment]
Feature already implemented, as [documented](https://github.com/miraclx/xresilient/#xresilientfn-options).

Here's where the magic happens.
https://github.com/miraclx/xresilient/blob/3e5d13b78f89e7f782603ff9fe38cf984ad6082e/lib/index.js#L8-L11
The rest of the options are relayed into the ResilientStream constructor.

Also, in the new versions, you can modify or define the number of retries so long as the stream hasn't maxed out the active retries within the `retryCount` using the [`setRetries()`](https://github.com/miraclx/xresilient/#resilientstream_setretries) method

Consider pulling recent versions.
