### ISSUE TITLE
on finish not getting triggered

### ISSUE THREAD

**Issue by sarkistlt** [miraclx/xresilient#2]
Thanks for the package, exactly what I was looking for!

The only problem I have right now, is when I'm wrapping my readStream, it stops emitting on finish event when stream is complete, and for some reason if I'll listen for on `end` it get's triggered first before stream pipe is started

**Comment by miraclx** [comment]
By default, the resilient stream would only emit the `end` event when the underlying stream ends i.e emits the `end` event.
Which is the expected behavior.

Please send an example of this code so I can work with that.

It might be that your readStream emits the `end` event for a different purpose.

**Comment by miraclx** [comment]
What type of readable stream are you working with?

Going by the [docs](https://nodejs.org/api/stream.html#stream_event_end), `The 'end' event is emitted when there is no more data to be consumed from the stream.`

While writable streams and only those are expected to emit the [`finish`](https://nodejs.org/api/stream.html#stream_event_finish) event

The resilient stream is intended to work with readable streams and only those.
Working with writable streams could get tricky and messy, so to say

Maybe you're using a Duplex stream?

Or log all the events being emitted by your `readStream` so you can track the emit order.
Please send all these details in your next comment.

Thanks.

**Comment by sarkistlt** [comment]
I'm using google storage read/write streams, so my code to get read stream looks like the following:

```js
const readStream = resilientStream({
      retries: 5,
      getReadStream: ({ bytesRead, retryCount, lastErr }) => {
        logger.log('info', `retry count = ${retryCount}`);
        if (retryCount >= 5) {
          reject(lastErr);
        } else {
          return remoteFile.createReadStream({ start: bytesRead });
        }
      },
    });
```

so if I'll try to listen `finish` or `end` event on th read stream (which I use to do before) right now it doesn't work, my guess it happens because of `stream.Transform`. I end up listening for  `finish` event on the write stream.

**Comment by miraclx** [comment]
Hi again @sarkistlt, from the snippet above
You got your API implementation all wrong.

1. The `xresilient` function takes at least one of two arguments [[docs]](https://github.com/miraclx/xresilient/#xresilientfn-options)
The first, being a function that conditionally returns the `readStream`
The second, being the options object
2. you don't have to write the checking mechanism for the number of retries as the resilient stream does that by itself. Once it hits the maximum number of retries, it throws the `lastErr` on the resilient stream itself and destroys the underlying streams.
As seen here
https://github.com/miraclx/xresilient/blob/c56757dbff19338b943c0e5b801d0581f2e83398/lib/index.js#L38-L44
All you have to do is listen for the error event.
Which will supply the last caught `'error'` event that maxed out the total number of valid retries.

Also, xresilient has been rewritten to address the `stream.Transform` issue.
Underwent major reconstruction 294204a681dc201991080ea135b6060075bf4e4b
By default, the resilient stream is now a [Readable stream][NodeJS.ReadableStream]

Rewriting the snippet you posted above
``` javascript
const readStream = resilientStream(
  ({bytesRead, retryCount}) => {
    logger.log('info', `retry count = ${retryCount}`);
    return remoteFile.createReadStream({start: bytesRead});
  },
  {retries: 5},
).on('error', reject);
```

[NodeJS.ReadableStream]: https://nodejs.org/api/stream.html#stream_class_stream_readable

**Comment by sarkistlt** [comment]
Hi @miraclx thanks, I'll check new version.
My implementation wasn't wrong, I was using my forked version, and just made some minor changes in how to configure it. So my snippet is equivalent of what you suggested.

**Comment by miraclx** [comment]
Oh
You might have to rebase that
The source has undergone major remodifications.
Please test it with the latest revision and see what happens
